In [1]:
import pandas as pd
import numpy as np

In [5]:
#Convert all to a data frame
df = pd.read_csv("Crosswalk file update, 4-25(Text).csv", encoding="utf-8")
df.columns

Index(['File ID', 'Start Date', 'End date', 'Status', 'Respondent ID', 'S1',
       'AGE_RANGE', 'S2', 'S3_R1', 'S3_R2', 'S3_R3', 'S3_R4', 'S3_R5', 'S3_R6',
       'S3_R7', 'S3_R8', 'S3_R9', 'S3_R10', 'S3_R99', 'S4', 'S5_BRAND1',
       'S5_BRAND2', 'S5_BRAND3', 'S5_BRAND4', 'S5_BRAND5', 'S5_BRAND6',
       'S5_BRAND99', 'S6', 'S7_BRAND1', 'S7_BRAND2', 'S7_BRAND3', 'S7_BRAND4',
       'S7_BRAND5', 'S7_BRAND6', 'ELIGIBLE_BRAND1', 'ELIGIBLE_BRAND2',
       'ELIGIBLE_BRAND3', 'ELIGIBLE_BRAND4', 'ELIGIBLE_BRAND5',
       'ELIGIBLE_BRAND6', 'S8_BRAND1', 'S8_BRAND2', 'S8_BRAND3', 'S8_BRAND4',
       'S8_BRAND5', 'S8_BRAND6', 'S9', 'S10', 'S11', 'S12', 'S13', 'S14',
       'MOS_HASH'],
      dtype='object')

In [9]:
#Filter to get the rigth schema
columns_to_keep = ['File ID', 'Respondent ID','S1','AGE_RANGE','S2','S4','S5_BRAND1', 'S5_BRAND2', 
'S5_BRAND3','S5_BRAND4','S5_BRAND5','S5_BRAND6','S6','S7_BRAND1','S7_BRAND2','S7_BRAND3',
'S7_BRAND4','S8_BRAND1','S8_BRAND2','S8_BRAND3','S8_BRAND4','S9','S10', 'S11', 'S12']
filtered_df = df[columns_to_keep]

filtered_df.head(5)

,File ID,Respondent ID,S1,AGE_RANGE,S2,S4,S5_BRAND1,S5_BRAND2,S5_BRAND3,S5_BRAND4,...,S7_BRAND3,S7_BRAND4,S8_BRAND1,S8_BRAND2,S8_BRAND3,S8_BRAND4,S9,S10,S11,S12
0,ca66cb4696244dd893c6f67b91f0a923#104,1b36ec24-0064-4977-af69-415cd755a4ad,33,28-49,Male,No,YouTube,Facebook,Instagram,TikTok,...,Over 6 hours,1 to 2 hours,1 to 2 hours,1 to 2 hours,1 to 2 hours,Less than 30 minutes,No,Yes,iOS (Apple),Central Standard Time
1,647f8d33c75d4189bd33d26f0bc519b9#399,361d2ad1-c4b6-49e3-82b9-6f8d56196a94,33,28-49,Female,Yes,YouTube,Facebook,NO TO: Instagram,NO TO: TikTok,...,NaN,NaN,30 minutes to 1 hour,2 to 4 hours,NaN,NaN,No,Yes,iOS (Apple),Eastern Standard Time
2,5788abbffedf441da26a3c9c03a12d00#242,3fe53820-1b01-49f2-9b18-bb0237a3ba5b,41,28-49,Male,Yes,YouTube,Facebook,Instagram,TikTok,...,Over 6 hours,Over 6 hours,1 to 2 hours,1 to 2 hours,1 to 2 hours,2 to 4 hours,No,Yes,Android,Eastern Standard Time
3,20da053f76a34bd69f33915feb1de5aa#801,5d8af917-5c0c-4ae3-8ef0-5cae33338f73,40,28-49,Female,Yes,YouTube,Facebook,NO TO: Instagram,TikTok,...,NaN,2 to 4 hours,1 to 2 hours,1 to 2 hours,NaN,2 to 4 hours,Yes,Yes,Android,Eastern Standard Time
4,dd16d8d542614b6abcbdfbce61859022#716,ccff562e-1ee9-4320-83c0-5595a7a9beb0,24,18-27,Female,Yes,YouTube,Facebook,Instagram,NO TO: TikTok,...,2 to 4 hours,NaN,Over 6 hours,2 to 4 hours,1 to 2 hours,NaN,No,Yes,iOS (Apple),Eastern Standard Time

In [ ]:
#Start transformation of the columns S5_BRAND to boolean
filtered_df['S5_BRAND1'] = filtered_df['S5_BRAND1'].apply(lambda x: True if x == 'YouTube' else False)
filtered_df['S5_BRAND2'] = filtered_df['S5_BRAND2'].apply(lambda x: True if x == 'Facebook' else False)
filtered_df['S5_BRAND3'] = filtered_df['S5_BRAND3'].apply(lambda x: True if x == 'Instagram' else False)
filtered_df['S5_BRAND4'] = filtered_df['S5_BRAND4'].apply(lambda x: True if x == 'TikTok' else False)
filtered_df['S5_BRAND5'] = filtered_df['S5_BRAND5'].apply(lambda x: True if x == 'Google search' else False)
filtered_df['S5_BRAND6'] = filtered_df['S5_BRAND6'].apply(lambda x: True if x == 'Amazon' else False)

In [ ]:
#Convert S7 and S8 brands into integers with clusters
# Define your mapping
time_mapping = {
    "Less than 30 minutes": 1,
    "30 minutes to 1 hour": 2,
    "1 to 2 hours": 3,
    "2 to 4 hours": 4,
    "4 to 6 hours": 5,
    "Over 6 hours": 6
}

# Apply mapping to create a new integer column
filtered_df['S7_BRAND1'] = filtered_df['S7_BRAND1'].map(time_mapping)
filtered_df['S7_BRAND2'] = filtered_df['S7_BRAND2'].map(time_mapping)
filtered_df['S7_BRAND3'] = filtered_df['S7_BRAND3'].map(time_mapping)
filtered_df['S7_BRAND4'] = filtered_df['S7_BRAND4'].map(time_mapping)
filtered_df['S8_BRAND1'] = filtered_df['S8_BRAND1'].map(time_mapping)
filtered_df['S8_BRAND2'] = filtered_df['S8_BRAND2'].map(time_mapping)
filtered_df['S8_BRAND3'] = filtered_df['S8_BRAND3'].map(time_mapping)
filtered_df['S8_BRAND4'] = filtered_df['S8_BRAND4'].map(time_mapping)

In [18]:
#Convert the time_zone
# Define your mapping
time_zone_mapping = {
    "Eastern Standard Time": 1,
    "Central Standard Time": 2,
    "Mountain Standard Time": 3,
    "Pacific Standard Time": 4,
    "Alaska Standard Time": 5,
    "Hawaii Standard Time": 6,
    "Other": 7
}

# Apply mapping to create a new integer column
df['S12'] = df['S12'].map(time_zone_mapping)

In [23]:
filtered_df.columns = [
    'file_id', 'user_id', 'age', 'age_range', 'gender', 'children_3plus',
    'youtube_pastmonth', 'facebook_pastmonth', 'instagram_pastmonth', 'tiktok_pastmonth',
    'googlesearch_pastmonth', 'amazon_pastmonth', 'amazon_app_pastmonth',
    'youtube_weekly_timespent', 'facebook_weekly_timespent', 'instagram_weekly_timespent',
    'tiktok_weekly_timespent', 'youtube_daily_timespent', 'facebook_daily_timespent',
    'instagram_daily_timespent', 'tiktok_daily_timespent', 'youtube_premium',
    'amazon_prime', 'mobile_type', 'time_zone'
]

# Then assign to final_df if needed
final_df = filtered_df

final_df

,file_id,user_id,age,age_range,gender,children_3plus,youtube_pastmonth,facebook_pastmonth,instagram_pastmonth,tiktok_pastmonth,...,instagram_weekly_timespent,tiktok_weekly_timespent,youtube_daily_timespent,facebook_daily_timespent,instagram_daily_timespent,tiktok_daily_timespent,youtube_premium,amazon_prime,mobile_type,time_zone
0,ca66cb4696244dd893c6f67b91f0a923#104,1b36ec24-0064-4977-af69-415cd755a4ad,33,28-49,Male,No,YouTube,Facebook,Instagram,TikTok,...,Over 6 hours,1 to 2 hours,1 to 2 hours,1 to 2 hours,1 to 2 hours,Less than 30 minutes,No,Yes,iOS (Apple),Central Standard Time
1,647f8d33c75d4189bd33d26f0bc519b9#399,361d2ad1-c4b6-49e3-82b9-6f8d56196a94,33,28-49,Female,Yes,YouTube,Facebook,NO TO: Instagram,NO TO: TikTok,...,NaN,NaN,30 minutes to 1 hour,2 to 4 hours,NaN,NaN,No,Yes,iOS (Apple),Eastern Standard Time
2,5788abbffedf441da26a3c9c03a12d00#242,3fe53820-1b01-49f2-9b18-bb0237a3ba5b,41,28-49,Male,Yes,YouTube,Facebook,Instagram,TikTok,...,Over 6 hours,Over 6 hours,1 to 2 hours,1 to 2 hours,1 to 2 hours,2 to 4 hours,No,Yes,Android,Eastern Standard Time
3,20da053f76a34bd69f33915feb1de5aa#801,5d8af917-5c0c-4ae3-8ef0-5cae33338f73,40,28-49,Female,Yes,YouTube,Facebook,NO TO: Instagram,TikTok,...,NaN,2 to 4 hours,1 to 2 hours,1 to 2 hours,NaN,2 to 4 hours,Yes,Yes,Android,Eastern Standard Time
4,dd16d8d542614b6abcbdfbce61859022#716,ccff562e-1ee9-4320-83c0-5595a7a9beb0,24,18-27,Female,Yes,YouTube,Facebook,Instagram,NO TO: TikTok,...,2 to 4 hours,NaN,Over 6 hours,2 to 4 hours,1 to 2 hours,NaN,No,Yes,iOS (Apple),Eastern Standard Time
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,40f3755d31a84eb981188ce3711fb04d#919,6af5c7c1-39ba-489c-a60b-47c6f9f043e3,29,28-49,Female,Yes,YouTube,Facebook,Instagram,NO TO: TikTok,...,2 to 4 hours,NaN,Less than 30 minutes,1 to 2 hours,30 minutes to 1 hour,NaN,No,Yes,Android,Central Standard Time
300,1a234ed0d83343aca4afcb58a56f53a2#923,94aba406-39ff-428d-96e5-0aae12bd41af,27,18-27,Female,Yes,YouTube,Facebook,Instagram,TikTok,...,Over 6 hours,Over 6 hours,2 to 4 hours,30 minutes to 1 hour,2 to 4 hours,2 to 4 hours,No,Yes,iOS (Apple),Central Standard Time
301,e59f531b662b4755bc673d00a8fdb78a#262,312e3a95-bbd1-41db-9dda-50c125a96120,49,28-49,Female,No,YouTube,NO TO: Facebook,Instagram,NO TO: TikTok,...,Less than 30 minutes,NaN,Less than 30 minutes,NaN,Less than 30 minutes,NaN,No,No,Android,Pacific Standard Time
302,f3eeafe44ec94901b14a0b965961ef64#835,7e3df7bf-fb7a-4cb6-92ea-95ef27be96e9,39,28-49,Female,Yes,YouTube,Facebook,Instagram,TikTok,...,2 to 4 hours,4 to 6 hours,Less than 30 minutes,1 to 2 hours,1 to 2 hours,2 to 4 hours,No,Yes,iOS (Apple),Eastern Standard Time
303,acdbf6c8202047cc8c4fb46ce04be0d2#514,d8d40811-9ce4-404a-adca-b7843b5ca670,40,28-49,Female,No,YouTube,Facebook,Instagram,TikTok,...,2 to 4 hours,2 to 4 hours,Less than 30 minutes,Less than 30 minutes,Less than 30 minutes,Less than 30 minutes,No,NaN,Android,Pacific Standard Time